export const DATA_ACCOUNT_CODE = 'MPSP_ACCT_CODE';
export const DATA_DEPARTMENT = 'MPSP_DPMT_CODE';
export const DATA_PERIOD = 'MPSP_PERD_CODE';
export const DATA_BANK_CODE = 'MPSP_BANK_CODE';
export const DATA_STATION = 'MPSP_STTN_CODE';
